//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by lang_German.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_WPN_SETUP                   101
#define IDD_SUBCHANNELS_CFG             102
#define IDD_IN_BAR_DLG                  103
#define IDP_OLE_INIT_FAILED             104
#define IDR_BROWSEVIEW_TMPL             105
#define IDR_HOSTBAR                     106
#define IDD_MISC                        106
#define IDR_LANGBAR                     107
#define IDD_LOGIN_CFG                   108
#define IDS_BEER                        109
#define IDR_MESSAGEVIEW_TMPL            110
#define IDR_roboServTYPE                111
#define IDR_START_NODESERVER            112
#define IDR_SYSTRAY                     113
#define IDR_TOOLBAR2                    114
#define IDR_USERLIST                    115
#define IDS_ADD                         116
#define IDS_AUTHOR                      117
#define IDS_AUTOJOIN_ADD                118
#define IDS_AUTOJOIN_REMOVE             119
#define IDS_AVERAGE_LAG                 120
#define IDS_AVERAGE_LAG_CHAT            121
#define IDS_AWAY_BACK                   122
#define IDS_AWAY_CONTROL                123
#define IDS_AWAY_SILENTBACK             124
#define IDS_AWAYCTRL                    125
#define IDS_BANLISTING                  126
#define IDS_BANLISTINGEND               127
#define IDR_MAINFRAME                   128
#define IDS_BATH                        129
#define IDS_BANLISTINGSTART             130
#define IDS_BITMAP_FILTER               131
#define IDS_BROWSE_CMPLT                132
#define IDS_BROWSE_HEAD                 133
#define IDS_BROWSE_TITLE                134
#define IDS_CFG_COLORS                  135
#define IDS_CFG_EXT                     136
#define IDS_CFG_FUN                     137
#define IDS_CFG_GENERAL                 138
#define IDS_CFG_MSG                     139
#define IDS_CFG_SERVER                  140
#define IDS_CFG_SND                     141
#define IDS_CHANNELLIST                 142
#define IDS_CHANNELSTATS1               143
#define IDS_CHANNELSTATS2               144
#define IDS_CHANNELSTATS3               145
#define IDS_CLIENTDISC                  146
#define IDS_CLIENTDISC2                 147
#define IDS_CLIENTDISC3                 148
#define IDS_COMMAND_EXECUTED            149
#define IDS_COMMAND_NOTUNDERSTOOD       150
#define IDS_COMMANDBAR                  151
#define IDS_CONNECTING                  152
#define IDS_CONNECTION_RETRY            153
#define IDS_CUSTOMIZE                   154
#define IDS_DEFAULT_KEYMSG              155
#define IDS_DEFAULT_MOTD                156
#define IDS_DEFAULT_TOPIC               157
#define IDS_DESC                        158
#define IDS_DISPLAY_USERLEVEL           159
#define IDS_EDIT_MENU                   160
#define IDS_EMO_ACT                     161
#define IDS_EMO_FILE                    162
#define IDS_ERROR_BG_LOAD               163
#define IDS_ERROR_CMDEMPTY              164
#define IDS_ERROR_COM                   165
#define IDS_ERROR_COMCTRL               166
#define IDS_ERROR_CONNECTFORCED         167
#define IDS_ERROR_CONNECTING            168
#define IDS_ERROR_FILE_GENERIC          169
#define IDS_ERROR_FIXME                 170
#define IDS_ERROR_INITSPEECH            171
#define IDS_ERROR_INVALID_PLUGIN        172
#define IDS_ERROR_INVALID_SOCKET        173
#define IDS_ERROR_KICKED                174
#define IDS_ERROR_LOGFILE_OPEN          175
#define IDS_ERROR_LOGFILE_WRITE         176
#define IDS_ERROR_LOGIN_KEY             177
#define IDS_ERROR_LOGIN_REJECTED        178
#define IDS_ERROR_LOGIN_UNKNOWN         179
#define IDS_ERROR_MISSING_INPUT         180
#define IDS_ERROR_MX353ONLY             181
#define IDS_ERROR_NAME_INVALID          182
#define IDS_ERROR_NAME_LONG             183
#define IDS_ERROR_NAME_SHORT            184
#define IDS_ERROR_NAMES_EMPTY           185
#define IDS_ERROR_NETWORK               186
#define IDS_ERROR_NO_CHATSERVER         187
#define IDS_ERROR_NO_SELECTION          188
#define IDS_ERROR_NODEREQUIRED          189
#define IDS_ERROR_NOTUNDERSTOOD         190
#define IDS_ERROR_NOTUNDERSTOOD_SEND    191
#define IDS_ERROR_PERMISSIONDENIED_SEND 192
#define IDS_ERROR_PLAYWAVE              193
#define IDS_ERROR_PLUGIN_INIT           194
#define IDS_ERROR_PLUGIN_LOAD           195
#define IDS_ERROR_PLUGIN_OLDAPI         196
#define IDS_ERROR_PORT                  197
#define IDS_ERROR_REDIRECT_ROOMNAMEINVALID 198
#define IDS_ERROR_REMOVE_PLUGIN         199
#define IDS_ERROR_ROOMLENGTH            200
#define IDS_ERROR_ROOMNAME_EMPTY        201
#define IDS_ERROR_ROOMNAME_INVALID      202
#define IDS_ERROR_SELECT_PLUGIN         203
#define IDS_ERROR_SELECTEVENT           204
#define IDS_ERROR_SERVER_FILE           205
#define IDS_ERROR_SERVER_HANDSHAKE      206
#define IDS_ERROR_SERVER_HOST           207
#define IDS_ERROR_SERVER_KEYEXISTS      208
#define IDS_ERROR_SERVER_NOKEY          209
#define IDS_ERROR_SERVER_NOROOM         210
#define IDS_ERROR_SERVER_ONEROOMPERCONSOLE 211
#define IDS_ERROR_SERVER_SYNTAXERROR    212
#define IDS_ERROR_SERVER_WRONGKEY       213
#define IDS_ERROR_TIMEOUT               214
#define IDS_ERROR_UNKNOWN_ID            215
#define IDS_ERROR_WINSOCK               216
#define IDS_EXITQUESTION                217
#define IDS_FILTEREDCHANNELS            218
#define IDS_FINISHED                    219
#define IDS_FIXME_NAME_ERROR            220
#define IDS_FIXME_UNKNOWN_COMMAND       221
#define IDS_FLOODBLOCK                  222
#define IDS_FOOD                        223
#define IDS_FRESHAIR                    224
#define IDS_GIVE_VOICE                  225
#define IDS_GOOGLE_STR                  226
#define IDS_HANDSHAKE_START             227
#define IDS_HIDDENLISTING               228
#define IDS_HIDDENLISTINGEND            229
#define IDS_HIDDENLISTINGSTART          230
#define IDS_HILITE_LOADED               231
#define IDS_HOSTBAR                     232
#define IDS_IGNORED                     233
#define IDS_IGNORED_MX353               234
#define IDS_IMAGE_FILTER                235
#define IDS_KICKBAN_5                   236
#define IDS_LANGUAGE                    237
#define IDS_LIST                        238
#define IDS_LOG_START                   239
#define IDS_LOGIN_OK                    240
#define IDS_LURKMETER                   241
#define IDS_LURKMETER1                  242
#define IDS_LURKMETER2                  243
#define IDS_MODES                       244
#define IDS_NEWPM                       245
#define IDS_NOSUCHBAN                   246
#define IDS_NOTYOURBUISNESS             247
#define IDS_NOVOICE                     248
#define IDS_PING                        249
#define IDS_PLUGIN                      250
#define IDS_PM_AWAY                     251
#define IDS_PM_NOTIME_WRITES            252
#define IDS_PM_NOTIME_YOUWRITE          253
#define IDS_PM_TIME_WRITES              254
#define IDS_PM_TIME_YOUWRITE            255
#define IDS_REALLYSTOP                  256
#define IDS_RECONNECTING                257
#define IDS_REDIRECT_USER               258
#define IDS_REDIRECTING                 259
#define IDS_REJOIN_ROOM                 260
#define IDS_REMOVE_PLUGIN               261
#define IDS_REMOVE_VOICE                262
#define IDS_RENAMEMSG                   263
#define IDS_RESTART                     264
#define IDS_ROBOMX_ROOMSERVER           265
#define IDS_ROOMINVISIBLE               266
#define IDS_ROOMIP                      267
#define IDS_ROOMLIST                    268
#define IDS_ROOMNAME                    269
#define IDS_ROOMNOWVIS                  270
#define IDS_ROOMPORT                    271
#define IDS_ROOMRENAME                  272
#define IDS_ROOMS_ETA                   273
#define IDS_RTF_BLOCK                   274
#define IDS_SEND_WHOIS                  275
#define IDS_SENDPM                      276
#define IDS_SERVER_CFG_LOADED           277
#define IDS_SERVER_CFG_SAVED            278
#define IDS_SERVER_CLIENTS              279
#define IDS_SERVER_EXILED               280
#define IDS_SERVER_FILTER               281
#define IDS_SERVER_HELP                 282
#define IDS_SERVER_IPCLIENT             283
#define IDS_SERVER_JOINS                284
#define IDS_SERVER_JOINSFAILED          285
#define IDS_SERVER_KICKED               286
#define IDS_SERVER_KICKEDBANNED         287
#define IDS_SERVER_MCMA                 288
#define IDS_SERVER_MSGS                 289
#define IDS_SERVER_MX331                290
#define IDS_SERVER_MX353                291
#define IDS_SERVER_OTHER                292
#define IDS_SERVER_RABBIT               293
#define IDS_SERVER_RCMS                 294
#define IDS_SERVER_RMX                  295
#define IDS_SERVER_ROBOMX               296
#define IDS_SERVER_ROOMRENAME           297
#define IDS_SERVER_SETMODE              298
#define IDS_SERVER_STATS                299
#define IDS_SERVER_STATSEND             300
#define IDS_SERVER_SUCCESS              301
#define IDS_SERVER_TERMINATED           302
#define IDS_SERVER_UNBAN                303
#define IDS_SERVER_UPTIME               304
#define IDS_SERVER_WINMX353             305
#define IDS_SERVERNEW                   306
#define IDS_SETTINGS                    307
#define IDS_SLEEP                       308
#define IDS_SMOKE                       309
#define IDS_SOUND                       310
#define IDS_STORE                       311
#define IDS_TOOL_JOINVARIABLES          312
#define IDS_TOOL_MSGVARIABLES           313
#define IDS_TOOL_PARTVARIABLES          314
#define IDS_TOOL_SERVERVARIABLES        315
#define IDS_TOOL_WAVARIABLES            316
#define IDS_TOOL_WILDCARDS              317
#define IDS_TOOLBAR                     318
#define IDS_TOPIC                       319
#define IDS_TOPIC2                      320
#define IDS_TRIGGER                     321
#define IDS_TV                          322
#define IDS_UNIGNORE                    323
#define IDS_UNIGNORE_MX353              324
#define IDS_UPDATE_AVAILABLE            325
#define IDS_USERCLIENT                  326
#define IDS_USERFILES                   327
#define IDS_USERHOSTNAME                328
#define IDS_USERIP                      329
#define IDS_USERLINE                    330
#define IDS_USERLIST                    331
#define IDS_USERLIST_NODE               332
#define IDS_USERLIST_SHORT              333
#define IDS_USERMNU                     334
#define IDS_USERMODE                    335
#define IDS_USERMODES                   336
#define IDS_USERNAME                    337
#define IDS_USERS                       338
#define IDS_USERSTATS                   339
#define IDS_VIS                         340
#define IDS_WARN_USERNAMEHIJACK         341
#define IDS_WAVE_FILTER                 342
#define IDS_WELCOME1                    343
#define IDS_WELCOME2                    344
#define IDS_WHOIS_1                     345
#define IDS_WHOIS_2                     346
#define IDS_WHOIS_ERROR                 347
#define IDS_WINMX353_WRONGJOIN_WARNING  348
#define IDS_WORK                        349
#define IDS_WPN_CONNECTED               350
#define IDS_WPN_CONNECTING              351
#define IDS_WPN_DISCONNECTED            352
#define IDS_WPN_WARNING                 353
#define IDS_ZZZZZZZZ                    354
#define IDB_ROBOSERV                    355
#define IDB_BOX_IMAGES_XP_BLUE          356
#define IDD_OPENCONFIG                  357
#define IDI_QUESTION_ICON               358
#define IDS_CHANNEL_START               359
#define IDS_CHANNEL_STOP                360
#define IDS_SUBCHANNEL_CLOSED           361
#define IDS_SUBCHANNEL_NOTFOUND         362
#define IDS_PUBLIC                      363
#define IDS_PRIVATE                     364
#define IDS_PASSWORDEMPTY               365
#define IDS_NOCHANNELLOGIN              366
#define IDS_NOUSERMODE                  367
#define IDS_LOGINEXISTS                 368
#define IDS_NOSELECTION                 369
#define IDS_DELETELOGIN                 370
#define IDS_ADVERTISE_ROSE              371
#define IDS_INIT_1                      372
#define IDS_INIT_2                      373
#define IDS_INIT_3                      374
#define IDS_INIT_4                      375
#define IDS_INIT_5                      376
#define IDS_INIT_6                      377
#define IDS_INIT_7                      378
#define IDD_UPDATE                      381
#define IDB_RADIOBOX_IMAGES_XP_BLUE     386
#define IDC_ADMINPASSWORD               1000
#define IDC_AUTO_OP_LOCALHOST           1001
#define IDC_BLOCK_MX331                 1002
#define IDC_COLOR                       1003
#define IDC_GOD_FILES                   1004
#define IDC_GOD_LINE                    1005
#define IDC_GOD_NAME                    1006
#define IDC_KEYMSG                      1007
#define IDC_LISTED                      1008
#define IDC_MOTD                        1009
#define IDC_SELECTION_NOSCROLL          1010
#define IDC_SINGLEUSER_PER_IP           1011
#define IDC_TOOL_353LOOPBACK            1012
#define IDC_TOPIC                       1013
#define IDC_VISIBLE                     1014
#define IDC_VOICEPASSWORD               1015
#define IDC_WELCOME                     1016
#define IDC_AUTOCLOSE                   1017
#define IDC_ENABLE_SUBS                 1018
#define IDC_SUB_CREATE_LEVEL            1019
#define IDC_LIMIT_NUMBER_SUBS           1020
#define IDC_MAX_SUBS                    1021
#define IDC_LOGINS                      1022
#define IDC_EDIT                        1023
#define IDC_DELETE                      1024
#define IDC_PASSWORD                    1025
#define IDC_VOICE                       1026
#define IDC_ADMIN                       1027
#define IDC_AGENT                       1028
#define IDC_ADD                         1029
#define IDC_NUSHI_URL                   1030
#define IDC_VOICE_DEFAULT               1030
#define IDC_KM_URL                      1031
#define IDC_ADMIN_DEFAULT               1031
#define IDC_ZHEN_URL                    1032
#define IDC_AGENT_DEFAULT               1032
#define IDC_MXCONTROL_URL               1033
#define IDC_PROFS_UI                    1034
#define IDC_STATIC_1                    1035
#define IDC_STATIC_2                    1036
#define IDC_STATIC_3                    1037
#define IDC_STATIC_4                    1038
#define IDC_STATIC_5                    1039
#define IDC_STATIC_6                    1040
#define IDC_STATIC_7                    1041
#define IDC_VALID_MAIN                  1042
#define IDC_VALID_SUB                   1043
#define IDC_ADVERTISE                   1044
#define IDC_BROWSE                      1045
#define IDC_URL                         1046
#define IDC_DISPLAY_MESSAGES            1047
#define IDC_COLOR_PERMISSION            1048
#define IDC_COMBO1                      1049
#define IDC_VOICE_WATCH                 1049
#define IDC_UPDATE_DETAILS              1050
#define IDC_UPDATE_PROGRESS             1051
#define IDC_SUB_FIRSTISSUPER            1052
#define IDC_ADMIN_WATCH                 1055
#define IDC_STATIC_A                    1056
#define IDC_STATIC_B                    1057
#define IDC_STATIC_PW                   1060
#define IDC_STATIC_C                    1062
#define IDC_STATIC_D                    1063
#define IDC_STATIC_E                    1064
#define IDC_MODERATED                   1065
#define IDC_STATIC_F                    1066
#define IDC_STATIC_G                    1067
#define IDC_SUBLIST                     1068
#define IDC_NO_NORMAL                   1069
#define IDC_PLUS_NORMAL                 1070
#define IDC_AT_NORMAL                   1071
#define IDC_NO_VOICE                    1072
#define IDC_PLUS_VOICE                  1073
#define IDC_AT_VOICE                    1074
#define IDC_NO_ADMIN                    1075
#define IDC_PLUS_ADMIN                  1076
#define IDC_AT_ADMIN                    1077
#define IDC_NO_AGENT                    1078
#define IDC_PLUS_AGENT                  1079
#define IDC_AT_AGENT                    1080
#define IDC_STATIC_H                    1082
#define IDC_STATIC_I                    1083
#define IDC_STATIC_J                    1084
#define ID_CHANNEL_CHANNELLIST          32771
#define ID_CHANNELS_FILTER              32772
#define ID_CHATROOM_ASCIIARTDESIGN      32773
#define ID_CHATROOM_CLEARSCREEN         32774
#define ID_CHATROOM_COPYROOMNAME        32775
#define ID_CHATROOM_DISPLAYINCHANNEL_AVERAGELAG 32776
#define ID_CHATROOM_DISPLAYINCHANNEL_SYSTEMINFO 32777
#define ID_CHATROOM_DISPLAYINCHANNEL_SYSTEMUPTIME 32778
#define ID_CHATROOM_REJOIN              32779
#define ID_DISPLAYINCHANNEL_PING        32780
#define ID_EXIT                         32781
#define ID_FILE_NEW2                    32782
#define ID_FILE_SAVECFG                 32783
#define ID_HELP_COMMANDHELP             32784
#define ID_HELP_VISITHOMEPAGE           32785
#define ID_HOSTCHANNEL                  32786
#define ID_LANGSWITCHER                 32787
#define ID_LIST_EDITHIGHLIGHTKEYWORDS   32788
#define ID_LIST_HIGHLIGHT               32789
#define ID_LIST_LOCKFOCUSONSELECTION    32790
#define ID_LIST_UPDATELIST              32791
#define ID_MUTE                         32792
#define ID_MYFILE_NEW                   32793
#define ID_NEXT                         32794
#define ID_POPUP_COPYROOMNAME           32795
#define ID_POPUP_COPYTOPIC              32796
#define ID_POPUP_LOOPBACKJOIN           32797
#define ID_PREV                         32798
#define ID_RECONNECT                    32799
#define ID_RENAME                       32800
#define ID_ROBOMX_CONNECTNEWCHANNEL     32801
#define ID_ROBOMX_OPENSERVERCONFIGURATION 32802
#define ID_ROBOMX_SAVESERVERCONFIGURATION 32803
#define ID_ROOMIP                       32804
#define ID_ROOMNAMEBOX                  32805
#define ID_ROOMPORT                     32806
#define ID_SEND_FAILED                  32807
#define ID_STOPCHANNEL                  32808
#define ID_SYSTRAY_RESTORE              32809
#define ID_USER_BROWSE                  32810
#define ID_USERLIST_ADDADMIN            32811
#define ID_USERLIST_ADDAGENT            32812
#define ID_USERLIST_BAN                 32813
#define ID_USERLIST_COPYIP              32814
#define ID_USERLIST_COPYUSERNAME        32815
#define ID_USERLIST_CUSTOMIZETHISMENU   32816
#define ID_USERLIST_GIVEVOICE           32817
#define ID_USERLIST_HIDE                32818
#define ID_USERLIST_IGNORE              32819
#define ID_USERLIST_KICK                32820
#define ID_USERLIST_KICKBAN             32821
#define ID_USERLIST_PRINTIP             32822
#define ID_USERLIST_PRINTUSERSTAT       32823
#define ID_USERLIST_READUSERMESSAGE     32824
#define ID_USERLIST_REDIRECT            32825
#define ID_USERLIST_REMOVEADMIN         32826
#define ID_USERLIST_REMOVEAGENT         32827
#define ID_USERLIST_REMOVEVOICE         32828
#define ID_USERLIST_SENDMESSAGE         32829
#define ID_USERLIST_SHOW                32830
#define ID_USERLIST_STATISTICS          32831
#define ID_USERLIST_UNBAN               32832
#define ID_USERLIST_UNIGNORE            32833
#define ID_USERLIST_USERMODES           32834
#define ID_USERLIST_WHOIS               32835
#define ID_VIEW_AUTOJOINMANAGER         32836
#define ID_VIEW_CHANNELBAR              32837
#define ID_VIEW_COLOR_CONTROLS          32838
#define ID_VIEW_FULL_SCREEN             32839
#define ID_VIEW_IGNOREDUSERS            32840
#define ID_VIEW_LIKE_OFFICE_2003        32841
#define ID_VIEW_LIKE_OFFICE_2K          32842
#define ID_VIEW_LIKE_OFFICE_XP          32843
#define ID_VIEW_LOGFILE                 32844
#define ID_VIEW_MENUBAR                 32845
#define ID_VIEW_OPTIONS                 32846
#define ID_VIEW_RESIZABLE_BAR_0         32847
#define ID_VIEW_RESIZABLE_BAR_1         32848
#define ID_VIEW_RESIZABLE_BAR_2         32849
#define ID_VIEW_RESIZABLE_BAR_3         32850
#define ID_VIEW_RESIZABLE_BAR_4         32851
#define ID_VIEW_SYSTEMCONSOLE           32852
#define ID_VIEW_TOOLBARS_LANGUAGEBAR    32853
#define ID_VIEW_TRUSTEDUSERS            32854
#define ID_WPN_REFRESH                  32855
#define ID_WPN_STATUS                   32856
#define ID_USERLIST_REMOVEGHOST         32857
#define ID_VIEW_LIKE_STUDIO_2005        32858
#define ID_FILE_COPYCHANNELNAME         32860
#define ID_FILE_COPYLOOPBACKNAME        32861
#define IDS_COLORS_DISABLE              61446
#define IDS_COLORS_EVERYONE             61447
#define IDS_COLORS_VOICED               61448
#define IDS_COLORS_ADMIN                61449
#define IDS_COLORS_AGENTS               61450
#define IDS_SUB_EVERYONE                61451
#define IDS_SUB_VOICED                  61452
#define IDS_SUB_ADMIN                   61453
#define IDS_SUB_AGENTS                  61454
#define IDS_SUB_HOST                    61455
#define IDS_NOGHOST                     61456
#define IDS_CHECK_UPDATE                61457
#define IDS_USERLEVELWARNING            61458
#define IDS_CMD_START                   61459
#define IDS_CMD_LOGIN                   61460
#define IDS_CMD_CHANNELNAME             61461
#define IDS_CMD_LISTCHANNELS            61462
#define IDS_CMD_CREATECHANNEL           61463
#define IDS_CMD_JOIN                    61464
#define IDS_CMD_NOCLR                   61465
#define IDS_CMD_ENABLECLR               61466
#define IDS_CMD_PRIVATE                 61467
#define IDS_CMD_OP                      61468
#define IDS_CMD_KICK                    61469
#define IDS_CMD_KICKBAN                 61470
#define IDS_CMD_BAN                     61471
#define IDS_CMD_UNBAN                   61472
#define IDS_CMD_LISTBANS                61473
#define IDS_CMD_EXILE                   61474
#define IDS_CMD_TOPIC                   61475
#define IDS_CMD_MOTD                    61476
#define IDS_CMD_LIMIT                   61477
#define IDS_CMD_MODES                   61478
#define IDS_CMD_STATA                   61479
#define IDS_CMD_STATB                   61480
#define IDS_IDS_CMD_ADMIN               61481
#define IDS_CMD_REMADMIN                61482
#define IDS_CMD_AGENT                   61483
#define IDS_CMD_IMPOSE                  61484
#define IDS_CMD_ADDAGENT                61485
#define IDS_CMD_REMAGENT                61486
#define IDS_CMD_ENABLEEXILE             61487
#define IDS_CMD_DISABLEEXILE            61488
#define IDS_CMD_END                     61489
#define IDS_STATUS_USERS                61490
#define IDS_STATUS_SUBROOMS             61491
#define IDS_SUBJOIN                     61492
#define IDS_JOINNOROOM                  61493
#define IDS_SUBEQUALMAIN                61494
#define IDS_SUBCREATED                  61495
#define IDS_CMD_SUBPART                 61496
#define IDS_STATUS_PRIMARIES            61497

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        387
#define _APS_NEXT_COMMAND_VALUE         32862
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           1150
#endif
#endif
