//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by lang_Template.rc
//
#define IDS_ERROR_CONNECTING            1
#define IDS_HANDSHAKE_START             2
#define IDS_ERROR_LOGIN_UNKNOWN         3
#define IDS_ERROR_LOGIN_KEY             4
#define IDS_ERROR_NO_CHATSERVER         5
#define IDS_ERROR_NETWORK               6
#define IDS_ERROR_LOGIN_REJECTED        7
#define IDS_LOGIN_OK                    8
#define IDS_ERROR_FIXME                 9
#define IDS_CONNECTING                  10
#define IDS_SERVER_RCMS                 11
#define IDS_SERVER_WINMX353             12
#define IDS_WINMX353_WRONGJOIN_WARNING  13
#define IDS_ERROR_LOGFILE_OPEN          14
#define IDS_REDIRECTING                 15
#define IDS_ERROR_REDIRECT_ROOMNAMEINVALID 16
#define IDS_ROOMRENAME                  17
#define IDS_FIXME_NAME_ERROR            18
#define IDS_FIXME_UNKNOWN_COMMAND       19
#define IDS_RTF_BLOCK                   20
#define IDS_EDIT_MENU                   21
#define IDS_USERS                       27
#define IDS_ERROR_TIMEOUT               50
#define IDS_ERROR_INVALID_SOCKET        51
#define IDS_ERROR_UNKNOWN_ID            52
#define IDS_PM_AWAY                     53
#define IDS_WPN_CONNECTING              54
#define IDS_ERROR_COMCTRL               55
#define IDS_WPN_CONNECTED               56
#define IDS_ERROR_WINSOCK               57
#define IDS_ERROR_ROOMNAME_EMPTY        78
#define IDS_ERROR_ROOMNAME_INVALID      79
#define IDS_TOPIC                       99
#define IDD_ABOUTBOX                    100
#define IDS_SERVER_FILTER               101
#define IDS_ROOMS_ETA                   102
#define IDS_CHANNELLIST                 103
#define IDS_TOOL_JOINVARIABLES          104
#define IDS_PING                        105
#define IDS_CLIENTDISC                  106
#define IDS_SERVER_ROBOMX               107
#define IDS_ROBOMX_ROOMSERVER           108
#define IDS_ERROR_SERVER_ONEROOMPERCONSOLE 109
#define IDS_ERROR_SERVER_SYNTAXERROR    110
#define IDS_SERVER_SUCCESS              111
#define IDS_ERROR_SERVER_HOST           112
#define IDS_SERVER_TERMINATED           113
#define IDS_ERROR_SERVER_NOROOM         114
#define IDS_ERROR_CMDEMPTY              115
#define IDS_ERROR_NOTUNDERSTOOD         116
#define IDS_SERVER_HELP                 117
#define IDS_ERROR_SERVER_HANDSHAKE      118
#define IDS_WARN_USERNAMEHIJACK         119
#define IDS_SERVER_SETMODE              120
#define IDS_SERVER_KICKED               121
#define IDS_DEFAULT_TOPIC               122
#define IDS_DEFAULT_MOTD                123
#define IDS_DEFAULT_KEYMSG              124
#define IDS_NOSUCHBAN                   125
#define IDS_SERVER_UNBAN                126
#define IDS_BANLISTINGSTART             127
#define IDR_MAINFRAME                   128
#define IDR_TOOLBAR2                    130
#define IDS_ERROR_SERVER_FILE           131
#define IDS_WPN_DISCONNECTED            132
#define IDR_roboServTYPE                133
#define IDD_IN_BAR_DLG                  134
#define IDS_COMMAND_EXECUTED            135
#define IDS_SERVER_CFG_SAVED            136
#define IDR_MESSAGEVIEW_TMPL            137
#define IDS_WPN_WARNING                 138
#define IDS_ERROR_NODEREQUIRED          139
#define IDR_USERLIST                    140
#define IDS_SERVER_ROOMRENAME           141
#define IDS_ERROR_CONNECTFORCED         142
#define IDS_NOVOICE                     143
#define IDR_SYSTRAY                     146
#define IDS_SERVER_EXILED               148
#define IDS_ERROR_NOTUNDERSTOOD_SEND    149
#define IDS_SERVER_CFG_LOADED           151
#define IDS_ERROR_PERMISSIONDENIED_SEND 165
#define IDS_HIDDENLISTINGSTART          177
#define IDS_HIDDENLISTINGEND            178
#define IDS_HIDDENLISTING               179
#define IDS_ERROR_COM                   180
#define IDS_CHANNELSTATS1               183
#define IDS_CHANNELSTATS2               184
#define IDS_CHANNELSTATS3               185
#define IDS_LURKMETER                   186
#define IDS_LURKMETER1                  187
#define IDS_LURKMETER2                  188
#define IDS_CLIENTDISC2                 189
#define IDS_CLIENTDISC3                 190
#define IDR_HOSTBAR                     191
#define IDS_ERROR_SERVER_WRONGKEY       192
#define IDR_LANGBAR                     193
#define IDC_LISTED                      1000
#define IDC_TOPIC                       1002
#define IDC_MOTD                        1003
#define IDC_KEYMSG                      1004
#define IDC_WELCOME                     1005
#define IDC_ADMINPASSWORD               1006
#define IDC_VOICEPASSWORD               1007
#define IDC_COLOR                       1008
#define IDS_TOPIC2                      1010
#define IDS_FINISHED                    1099
#define IDS_BANLISTING                  1101
#define IDS_BANLISTINGEND               1106
#define IDS_COMMAND_NOTUNDERSTOOD       1109
#define IDS_MODES                       1112
#define IDS_ERROR_SERVER_KEYEXISTS      1114
#define IDS_ERROR_SERVER_NOKEY          1120
#define IDS_USERMODES                   1123
#define IDC_SINGLEUSER_PER_IP           1143
#define IDC_BLOCK_MX331                 1145
#define IDC_GOD_NAME                    1148
#define IDC_VISIBLE                     1149
#define IDC_GOD_FILES                   1150
#define IDC_GOD_LINE                    1152
#define IDC_AUTO_OP_LOCALHOST           1154
#define ID_VIEW_MENUBAR                 32771
#define ID_VIEW_LIKE_OFFICE_2K          32772
#define ID_VIEW_LIKE_OFFICE_XP          32773
#define ID_VIEW_COLOR_CONTROLS          32774
#define ID_VIEW_RESIZABLE_BAR_0         32775
#define ID_VIEW_RESIZABLE_BAR_1         32776
#define ID_VIEW_RESIZABLE_BAR_2         32777
#define ID_EXIT                         32781
#define ID_CHANNEL_CHANNELLIST          32783
#define ID_VIEW_LIKE_OFFICE_2003        32784
#define ID_USERLIST_COPYUSERNAME        32787
#define ID_USERLIST_ADDADMIN            32792
#define ID_USERLIST_REMOVEADMIN         32793
#define ID_USERLIST_UNBAN               32794
#define ID_USERLIST_PRINTUSERSTAT       32795
#define ID_USERLIST_PRINTIP             32796
#define ID_USERLIST_IGNORE              32797
#define ID_USERLIST_UNIGNORE            32798
#define ID_USERLIST_CUSTOMIZETHISMENU   32799
#define ID_USERLIST_READUSERMESSAGE     32800
#define ID_CHATROOM_CLEARSCREEN         32802
#define ID_CHATROOM_COPYROOMNAME        32803
#define ID_NEXT                         32804
#define ID_PREV                         32805
#define ID_RECONNECT                    32806
#define IDR_START_NODESERVER            32807
#define ID_VIEW_FULL_SCREEN             32808
#define ID_CHATROOM_DISPLAYINCHANNEL_SYSTEMUPTIME 32810
#define ID_CHATROOM_DISPLAYINCHANNEL_SYSTEMINFO 32811
#define ID_CHATROOM_DISPLAYINCHANNEL_AVERAGELAG 32812
#define ID_VIEW_CHANNELBAR              32818
#define ID_CHATROOM_ASCIIARTDESIGN      32819
#define ID_POPUP_LOOPBACKJOIN           32837
#define ID_POPUP_COPYROOMNAME           32838
#define ID_POPUP_COPYTOPIC              32839
#define ID_VIEW_LOGFILE                 32860
#define ID_CHATROOM_REJOIN              32861
#define ID_ROBOMX_OPENSERVERCONFIGURATION 32882
#define ID_ROBOMX_SAVESERVERCONFIGURATION 32883
#define ID_VIEW_IGNOREDUSERS            32894
#define ID_VIEW_TRUSTEDUSERS            32895
#define ID_HELP_VISITHOMEPAGE           32921
#define ID_HOSTCHANNEL                  32922
#define ID_STOPCHANNEL                  32923
#define ID_ROOMNAMEBOX                  32924
#define ID_ROOMIP                       32925
#define ID_ROOMPORT                     32926
#define ID_USERLIST_STATISTICS          32927
#define ID_USERLIST_USERMODES           32928
#define ID_HELP_COMMANDHELP             32930
#define ID_LANGSWITCHER                 32931
#define ID_VIEW_TOOLBARS_LANGUAGEBAR    32932
#define ID_VIEW_RESIZABLE_BAR_4         41000
#define ID_USERLIST_ADDAGENT            41001
#define ID_RENAME                       41002
#define ID_USERLIST_REMOVEAGENT         41003
#define ID_VIEW_OPTIONS                 41004
#define ID_USERLIST_COPYIP              41005
#define ID_MYFILE_NEW                   41006
#define ID_USERLIST_GIVEVOICE           41007
#define ID_USERLIST_SENDMESSAGE         41008
#define ID_USERLIST_REMOVEVOICE         41009
#define ID_USERLIST_KICK                41010
#define ID_USERLIST_HIDE                41011
#define ID_USERLIST_KICKBAN             41012
#define ID_USERLIST_SHOW                41013
#define ID_USERLIST_BAN                 41014
#define ID_FILE_SAVECFG                 41015
#define ID_USERLIST_REDIRECT            41016
#define ID_SYSTRAY_RESTORE              41017
#define ID_FILE_NEW2                    57608
#define IDS_SERVER_KICKEDBANNED         61446
#define IDS_RESTART                     61447
#define IDS_REALLYSTOP                  61448
#define IDS_ROOMINVISIBLE               61449
#define IDS_ROOMNOWVIS                  61450
#define IDS_WELCOME1                    61451
#define IDS_WELCOME2                    61452
#define IDS_RENAMEMSG                   61453
#define IDS_ERROR_PORT                  61454
#define IDS_ERROR_ROOMLENGTH            61455
#define IDS_EXITQUESTION                61456
#define IDS_USERNAME                    61457
#define IDS_USERMODE                    61458
#define IDS_USERIP                      61459
#define IDS_USERCLIENT                  61460
#define IDS_USERFILES                   61461
#define IDS_USERLINE                    61462
#define IDS_USERLIST                    61463
#define IDS_COMMANDBAR                  61464
#define IDS_ROOMPORT                    61465
#define IDS_ROOMIP                      61466
#define IDS_ROOMNAME                    61467
#define IDS_HOSTBAR                     61468
#define IDS_VIS                         61469
#define IDS_TOOLBAR                     61470
#define IDS_LANGUAGE                    61471
#define IDS_SERVER_STATS                61472
#define IDS_SERVER_UPTIME               61473
#define IDS_SERVER_CLIENTS              61474
#define IDS_SERVER_MX331                61475
#define IDS_SERVER_MX353                61476
#define IDS_SERVER_IPCLIENT             61477
#define IDS_SERVER_RMX                  61478
#define IDS_SERVER_RABBIT               61479
#define IDS_SERVER_OTHER                61480
#define IDS_SERVER_JOINS                61481
#define IDS_SERVER_JOINSFAILED          61482
#define IDS_SERVER_MSGS                 61483
#define IDS_SERVER_STATSEND             61484
#define IDS_USERSTATS                   61485
#define IDS_USERHOSTNAME                61486
#define IDS_FLOODBLOCK                  61487

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
